# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Node.js image with npm pre-installed
FROM node:16-alpine AS builder

# Create and set the working directory
WORKDIR /app

# Copy all necessary files
COPY . .

# Install the dependencies
RUN npm install

# Build the server
RUN npm run build

# Create a new image for the actual server
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder image
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Define environment variables for Azure DevOps
ENV AZURE_DEVOPS_ORG=your-organization
ENV AZURE_DEVOPS_PROJECT=your-project
ENV AZURE_DEVOPS_TOKEN=your-personal-access-token

# Start the server
ENTRYPOINT ["node", "build/index.js"]